name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: agross

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd agross/agross-admin/
            git fetch origin
            git reset --hard origin/main
            git pull origin main --force
            npm install
            npm run build
            rm -rf /var/www/admin.agross.uz/dist
            cp -r dist /var/www/admin.agross.uz/
